### ISSUE TITLE
Add collaborators to this repo

### ISSUE THREAD

**Issue by Brianbla** [GHDev-TJC/caption-this#1]
## Comment below to be added as a collaborator

We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API. Once you comment, we will add you as a collaborator.

You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.

**Comment by robhizon26** [comment]
Hello

**Comment by vvenkachalam** [comment]
I am leaving a comment

**Comment by RpTJC** [comment]
Left a comment

**Comment by harun7** [comment]
Thanks Brian!

**Comment by preetiadvani** [comment]
Comment1

**Comment by Eregnon** [comment]
Hello, I'ma comment.

**Comment by JCpoz123** [comment]
Go Bears!

**Comment by utpalakhouri** [comment]
Great information

**Comment by bharathbhk** [comment]
hello

**Comment by gergomiho** [comment]
Hello

**Comment by Dean92** [comment]
Hi.

**Comment by zlaugTJC** [comment]
Hello

**Comment by danimal523** [comment]
hi

**Comment by shettiv** [comment]
Hi
